# `cargo xtask` is the per-machine operator. Darwin linker flags stay here so
# `cargo xtask` itself can compile on Matrix when Xcode's license is unsigned.
# Linux hosts ignore [target.*-apple-darwin].

[alias]
xtask = "run --package xtask --"

[target.aarch64-apple-darwin]
linker = "/Library/Developer/CommandLineTools/usr/bin/clang"
rustflags = [
    "-C",
    "link-arg=-isysroot",
    "-C",
    "link-arg=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk",
]

[target.x86_64-apple-darwin]
linker = "/Library/Developer/CommandLineTools/usr/bin/clang"
rustflags = [
    "-C",
    "link-arg=-isysroot",
    "-C",
    "link-arg=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk",
]
