/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_folderfilter_free: (a: number, b: number) => void;
export const artifact: (a: number, b: number) => [number, number, number, number];
export const artifact_as: (a: any) => [number, number, number, number];
export const artifact_chunks: (a: any, b: any) => [number, number, number];
export const drop_result: (a: number, b: number) => number;
export const extract_files: (a: any) => [number, number, number, number];
export const extract_timeout_ms: () => number;
export const folderfilter_enter: (a: number, b: number, c: number) => number;
export const folderfilter_new: (a: any) => [number, number, number];
export const format_tree: (a: any) => [number, number, number, number];
export const heavy_kind: (a: number, b: number) => number;
export const needs_worker: (a: number, b: number, c: number) => number;
export const pack_abort: () => void;
export const pack_add: (a: number, b: number) => [number, number];
export const pack_begin: (a: any) => [number, number, number];
export const pack_files: (a: any) => [number, number, number];
export const pack_finish: () => [number, number, number];
export const preview_file: (a: any) => [number, number, number];
export const pulp_version: () => [number, number];
export const render_result: (a: any) => [number, number, number];
export const scan_files: (a: any) => [number, number, number];
export const scan_keep: (a: any) => [number, number, number];
export const scan_unknown: (a: any) => [number, number, number, number];
export const smoke_pack: () => [number, number, number];
export const start: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
